// crates/app/src/routes/admin/users/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData, PageServerData, ActionData } from './$types';
	import * as Table from '$lib/components/ui/table';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import * as AlertDialog from '$lib/components/ui/alert-dialog';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import {
		MoreHorizontal,
		Search,
		ShieldCheck,
		ShieldOff,
		Ban,
		CircleCheck,
		Trash2,
		AlertCircle
	} from 'lucide-svelte';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	type Row = PageServerData['users'][number];

	let banTarget = $state<Row | null>(null);
	let deleteTarget = $state<Row | null>(null);
</script>

<div class="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-8">
	<div class="flex flex-wrap items-end justify-between gap-3">
		<div>
			<h1 class="text-2xl font-extrabold tracking-tight">Users</h1>
			<p class="text-sm text-muted-foreground">{data.total} total user{data.total === 1 ? '' : 's'}</p>
		</div>
		<form method="get" class="flex items-center gap-2">
			<div class="relative">
				<Search
					size={15}
					class="pointer-events-none absolute top-1/2 left-2.5 -translate-y-1/2 text-muted-foreground"
				/>
				<Input
					name="q"
					value={data.q}
					placeholder="Search name or email"
					class="w-56 pl-8"
				/>
			</div>
			<Button type="submit" variant="secondary">Search</Button>
		</form>
	</div>

	{#if form?.message}
		<div
			class="flex items-center gap-2 rounded-lg border border-destructive/25 bg-destructive/10 px-4 py-3 text-sm text-destructive"
		>
			<AlertCircle size={16} />
			{form.message}
		</div>
	{/if}

	<div class="rounded-xl border border-border bg-card/30">
		<Table.Root>
			<Table.Header>
				<Table.Row>
					<Table.Head>User</Table.Head>
					<Table.Head>Role</Table.Head>
					<Table.Head>Status</Table.Head>
					<Table.Head>Resources</Table.Head>
					<Table.Head>Joined</Table.Head>
					<Table.Head class="text-right">Actions</Table.Head>
				</Table.Row>
			</Table.Header>
			<Table.Body>
				{#each data.users as u (u.id)}
					{@const isSelf = u.id === data.user.id}
					<Table.Row>
						<Table.Cell>
							<div class="flex min-w-0 flex-col">
								<span class="flex items-center gap-1.5 font-medium">
									{u.name || '—'}
									{#if isSelf}<span class="text-xs text-muted-foreground">(you)</span>{/if}
								</span>
								<span class="truncate text-xs text-muted-foreground">{u.email}</span>
							</div>
						</Table.Cell>
						<Table.Cell>
							{#if u.role === 'admin'}
								<Badge variant="secondary">admin</Badge>
							{:else}
								<span class="text-sm text-muted-foreground">user</span>
							{/if}
						</Table.Cell>
						<Table.Cell>
							{#if u.banned}
								<Badge variant="destructive">banned</Badge>
							{:else if u.emailVerified}
								<Badge variant="outline">verified</Badge>
							{:else}
								<span class="text-sm text-muted-foreground">unverified</span>
							{/if}
						</Table.Cell>
						<Table.Cell class="text-muted-foreground">{u.resources}</Table.Cell>
						<Table.Cell class="text-muted-foreground">
							{new Date(u.createdAt).toLocaleDateString()}
						</Table.Cell>
						<Table.Cell class="text-right">
							<DropdownMenu.Root>
								<DropdownMenu.Trigger>
									{#snippet child({ props })}
										<Button variant="ghost" size="sm" disabled={isSelf} {...props}>
											<MoreHorizontal size={16} />
										</Button>
									{/snippet}
								</DropdownMenu.Trigger>
								<DropdownMenu.Content align="end" class="w-44">
									{#if u.role === 'admin'}
										<form method="post" action="?/setRole" use:enhance>
											<input type="hidden" name="id" value={u.id} />
											<input type="hidden" name="role" value="user" />
											<DropdownMenu.Item>
												{#snippet child({ props })}
													<button type="submit" class="flex w-full items-center gap-2" {...props}>
														<ShieldOff size={14} />
														Revoke admin
													</button>
												{/snippet}
											</DropdownMenu.Item>
										</form>
									{:else}
										<form method="post" action="?/setRole" use:enhance>
											<input type="hidden" name="id" value={u.id} />
											<input type="hidden" name="role" value="admin" />
											<DropdownMenu.Item>
												{#snippet child({ props })}
													<button type="submit" class="flex w-full items-center gap-2" {...props}>
														<ShieldCheck size={14} />
														Make admin
													</button>
												{/snippet}
											</DropdownMenu.Item>
										</form>
									{/if}

									{#if u.banned}
										<form method="post" action="?/unban" use:enhance>
											<input type="hidden" name="id" value={u.id} />
											<DropdownMenu.Item>
												{#snippet child({ props })}
													<button type="submit" class="flex w-full items-center gap-2" {...props}>
														<CircleCheck size={14} />
														Unban
													</button>
												{/snippet}
											</DropdownMenu.Item>
										</form>
									{:else}
										<DropdownMenu.Item onSelect={() => (banTarget = u)}>
											<Ban size={14} />
											Ban user
										</DropdownMenu.Item>
									{/if}

									<DropdownMenu.Separator />
									<DropdownMenu.Item variant="destructive" onSelect={() => (deleteTarget = u)}>
										<Trash2 size={14} />
										Delete
									</DropdownMenu.Item>
								</DropdownMenu.Content>
							</DropdownMenu.Root>
						</Table.Cell>
					</Table.Row>
				{:else}
					<Table.Row>
						<Table.Cell colspan={6} class="py-10 text-center text-muted-foreground">
							No users found.
						</Table.Cell>
					</Table.Row>
				{/each}
			</Table.Body>
		</Table.Root>
	</div>
</div>

<!-- Ban dialog -->
<AlertDialog.Root open={banTarget !== null} onOpenChange={(o) => !o && (banTarget = null)}>
	<AlertDialog.Content>
		<form method="post" action="?/ban" use:enhance={() => async ({ update }) => {
			banTarget = null;
			await update();
		}}>
			<input type="hidden" name="id" value={banTarget?.id} />
			<AlertDialog.Header>
				<AlertDialog.Title>Ban {banTarget?.name || banTarget?.email}?</AlertDialog.Title>
				<AlertDialog.Description>
					The user will be signed out immediately and unable to sign in until unbanned.
				</AlertDialog.Description>
			</AlertDialog.Header>
			<div class="my-4 flex flex-col gap-2">
				<Label for="reason">Reason (optional)</Label>
				<Input id="reason" name="reason" placeholder="e.g. Abuse of service" />
			</div>
			<AlertDialog.Footer>
				<AlertDialog.Cancel type="button">Cancel</AlertDialog.Cancel>
				<AlertDialog.Action type="submit" class="bg-destructive text-white hover:bg-destructive/90">
					Ban user
				</AlertDialog.Action>
			</AlertDialog.Footer>
		</form>
	</AlertDialog.Content>
</AlertDialog.Root>

<!-- Delete dialog -->
<AlertDialog.Root open={deleteTarget !== null} onOpenChange={(o) => !o && (deleteTarget = null)}>
	<AlertDialog.Content>
		<form method="post" action="?/remove" use:enhance={() => async ({ update }) => {
			deleteTarget = null;
			await update();
		}}>
			<input type="hidden" name="id" value={deleteTarget?.id} />
			<AlertDialog.Header>
				<AlertDialog.Title>Delete {deleteTarget?.name || deleteTarget?.email}?</AlertDialog.Title>
				<AlertDialog.Description>
					This permanently deletes the user and all their ports, domains and subdomains. This cannot
					be undone.
				</AlertDialog.Description>
			</AlertDialog.Header>
			<AlertDialog.Footer>
				<AlertDialog.Cancel type="button">Cancel</AlertDialog.Cancel>
				<AlertDialog.Action type="submit" class="bg-destructive text-white hover:bg-destructive/90">
					Delete
				</AlertDialog.Action>
			</AlertDialog.Footer>
		</form>
	</AlertDialog.Content>
</AlertDialog.Root>

// crates/app/app/pages/admin/users.vue
<script setup lang="ts">
import type { DropdownMenuItem, TableColumn } from '@nuxt/ui'
import { refDebounced } from '@vueuse/core'

definePageMeta({ layout: 'dashboard', middleware: 'admin' })
useSeoMeta({ title: 'Users - Relay' })

const { client, user: me } = useAuth()
const toast = useToast()
const confirm = useConfirm()

const search = ref('')
const q = refDebounced(search, 250)
const { data, refresh, status } = useFetch('/api/admin/users', { query: { q } })

type Row = NonNullable<typeof data.value>['users'][number]

const columns: TableColumn<Row>[] = [
  { accessorKey: 'name', header: 'User' },
  { accessorKey: 'role', header: 'Role' },
  { accessorKey: 'banned', header: 'Status' },
  { accessorKey: 'resources', header: 'Resources' },
  { accessorKey: 'createdAt', header: 'Joined' },
  { id: 'actions', header: '', meta: { class: { td: 'text-right w-12' } } }
]

async function run(action: () => Promise<{ error: { message?: string } | null }>, success: string) {
  const { error } = await action()
  if (error) {
    toast.add({ title: 'Action failed', description: error.message, color: 'error', icon: 'i-lucide-circle-alert' })
    return
  }
  toast.add({ title: success, color: 'success', icon: 'i-lucide-check' })
  await refresh()
}

// Ban dialog
const banTarget = ref<Row | null>(null)
const banReason = ref('')
const banOpen = computed({
  get: () => !!banTarget.value,
  set: (v) => { if (!v) banTarget.value = null }
})

async function submitBan() {
  const target = banTarget.value
  if (!target) return
  banTarget.value = null
  await run(() => client.admin.banUser({ userId: target.id, banReason: banReason.value || undefined }), `${target.name} banned`)
  banReason.value = ''
}

function actions(row: Row): DropdownMenuItem[][] {
  const isAdmin = row.role === 'admin'
  return [
    [{
      label: isAdmin ? 'Remove admin' : 'Make admin',
      icon: isAdmin ? 'i-lucide-shield-off' : 'i-lucide-shield-check',
      onSelect: () => run(() => client.admin.setRole({ userId: row.id, role: isAdmin ? 'user' : 'admin' }), 'Role updated')
    }, row.banned
      ? { label: 'Unban', icon: 'i-lucide-undo-2', onSelect: () => run(() => client.admin.unbanUser({ userId: row.id }), `${row.name} unbanned`) }
      : { label: 'Ban', icon: 'i-lucide-ban', onSelect: () => { banTarget.value = row } }],
    [{
      label: 'Delete user',
      icon: 'i-lucide-trash-2',
      color: 'error',
      onSelect: async () => {
        const ok = await confirm({
          title: `Delete ${row.name}?`,
          description: 'This permanently deletes the account and all of its reserved resources.',
          confirmLabel: 'Delete user'
        })
        if (ok) await run(() => client.admin.removeUser({ userId: row.id }), 'User deleted')
      }
    }]
  ]
}
</script>

<template>
  <UDashboardPanel id="admin-users">
    <template #header>
      <UDashboardNavbar title="Users">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="mx-auto flex w-full max-w-6xl flex-col gap-6">
        <div class="flex flex-wrap items-end justify-between gap-4">
          <div>
            <span class="eyebrow">[ Admin ]</span>
            <h1 class="mt-2 text-2xl font-semibold tracking-tight text-highlighted">
              Users
            </h1>
            <p class="mt-1 text-sm text-muted">
              {{ data?.total ?? 0 }} {{ data?.total === 1 ? 'account' : 'accounts' }}
            </p>
          </div>
          <UInput v-model="search" icon="i-lucide-search" placeholder="Search name or email" size="md" class="sm:w-72" />
        </div>

        <div class="relative border border-default">
          <Crosses />
          <UTable :data="data?.users ?? []" :columns :loading="status === 'pending'" empty="No users found.">
            <template #name-cell="{ row }">
              <div class="flex items-center gap-3">
                <UAvatar :alt="row.original.name" size="sm" :ui="{ root: 'rounded-none bg-accented', fallback: 'font-mono text-xs' }" />
                <div class="min-w-0">
                  <p class="truncate text-highlighted">
                    {{ row.original.name }}
                    <span v-if="row.original.id === me?.id" class="text-xs text-dimmed">(you)</span>
                  </p>
                  <p class="truncate text-xs text-muted">
                    {{ row.original.email }}
                  </p>
                </div>
              </div>
            </template>
            <template #role-cell="{ row }">
              <UBadge :label="row.original.role || 'user'" :variant="row.original.role === 'admin' ? 'solid' : 'outline'" />
            </template>
            <template #banned-cell="{ row }">
              <UTooltip v-if="row.original.banned" :text="row.original.banReason || 'No reason given'">
                <UBadge color="error" label="Banned" />
              </UTooltip>
              <UBadge v-else-if="row.original.emailVerified" color="success" label="Verified" />
              <span v-else class="text-xs text-dimmed">Unverified</span>
            </template>
            <template #resources-cell="{ row }">
              <span class="font-mono tabular-nums">{{ row.original.resources }}</span>
            </template>
            <template #createdAt-cell="{ row }">
              {{ formatDate(row.original.createdAt) }}
            </template>
            <template #actions-cell="{ row }">
              <UDropdownMenu v-if="row.original.id !== me?.id" :items="actions(row.original)" :content="{ align: 'end' }">
                <UButton icon="i-lucide-ellipsis" color="neutral" variant="ghost" size="sm" aria-label="Actions" />
              </UDropdownMenu>
            </template>
          </UTable>
        </div>
      </div>

      <UModal v-model:open="banOpen" :title="`Ban ${banTarget?.name ?? ''}`" description="All of their active sessions will be revoked." :ui="{ footer: 'justify-end bg-muted' }">
        <template #body>
          <UFormField label="Reason" hint="Optional">
            <UInput v-model="banReason" placeholder="e.g. Abuse of service" autofocus @keydown.enter="submitBan" />
          </UFormField>
        </template>
        <template #footer>
          <UButton label="Cancel" color="neutral" variant="outline" @click="banOpen = false" />
          <UButton label="Ban user" color="error" @click="submitBan" />
        </template>
      </UModal>
    </template>
  </UDashboardPanel>
</template>
